library(shiny)
library(shinythemes)
library(shinyjs)
library(plotly)
library(shinydashboard)
library(survival)
library(rapidpror)
country <- "Jamaica" # Jamaica, Philippines, South Africa, Malaysia
source("Functions.R")
source("srh_update_data.R")
source("srh_shiny.R")
srh_shiny()